<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUJ5DtL4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUJ5DtL4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUJ5DtL4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUJ5DtL4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUJ5DtL4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UJ5DtL4',
    'container.build_id' => '4337813c',
    'container.build_time' => 1550138338,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUJ5DtL4');
